ITEM.name					= "Revolver"
ITEM.plural				= "Revolvers"
ITEM.size					= 1
ITEM.cost					= 800
ITEM.model				= "models/weapons/w_357.mdl"
ITEM.batch				= 5
ITEM.store				= true
ITEM.description	= "A small .357 chambered revolver."
ITEM.ammo					= "357"
ITEM.weaponType		= TYPE_SMALL
ITEM.base					= "weapon"
