ITEM.name					= "AR2"
ITEM.plural				= "AR2s"
ITEM.size					= 2
ITEM.cost					= 3000
ITEM.model				= "models/weapons/w_irifle.mdl"
ITEM.batch				= 5
ITEM.store				= true
ITEM.description	= "A large standard issue assault-rifle."
ITEM.ammo					= "ar2"
ITEM.weaponType		= TYPE_LARGE
ITEM.base					= "weapon"
