ITEM.name					= "Rifle Rounds"
ITEM.size					= 1
ITEM.cost					= 1000
ITEM.model				= "models/items/boxmrounds.mdl"
ITEM.batch				= 10
ITEM.store				= true
ITEM.plural				= "Rifle Rounds"
ITEM.description	= "Rounds for the police AR2."
ITEM.base					= "ammo"
ITEM.ammo					= {"AR2", 30}
