ITEM.name					= "Rifle Rounds"
ITEM.plural				= "Rifle Rounds"
ITEM.size					= 1
ITEM.cost					= 1000
ITEM.model				= "models/items/boxmrounds.mdl"
ITEM.batch				= 10
ITEM.store				= true
ITEM.description	= "Rounds for any kind of automatic rifle."
ITEM.base					= "ammo"
ITEM.ammo					= {"ar2", 30}
